/* const ADD_NEW_BREED = "ADD_NEW_BREED"; */
const GET_BREED = "GET_BREED";
/* const GET_DETAIL = "GET_DETAIL";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const FILTER = "FILTER";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const SORT = "SORT";
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'; */

module.exports = {
  GET_BREED
/*   ADD_NEW_BREED,
  GET_DETAIL,
  GET_TEMPERAMENTS,
  FILTER,
  SEARCH_BY_NAME,
  SET_CURRENT_PAGE,
  SORT, */
};